export default [
  {
    "Agency_cd_ext": "PR-ELITE",
    "Agency_cd_nac": "M/PR-ELI",
    "Contract_ext": "CLT30A",
    "Contract_nac": "SEMANA(S) DE ANIVERS",
    "Cdeaccshtl": "",
    "Cdeaccsglf": "",
    "Accesshotel": "",
    "Accessgolf": "",
    "NumberAirfare": "",
    "PriceAirfare": 0.0,
    "AmountTaxFee": 0.0,
    "Category": "ANVWKS",
    "IsLBC": true,
    "IsResidence": false,
    "ProvPack": 0.0,
    "ExceededAirfare": 0.0,
    "TaxFeeProvis": 0.0,
    "CostProvis": 0.0,
    "AccessThanksGiving": true,
    "IsRestrictUse": false,
    "RECNUM": 472160.0,
    "COMPANY": 5.0,
    "APPLICATION": "4030396",
    "TYPE": "D8",
    "FOLIO": 6370.0,
    "FIRST": "DEMO",
    "LAST": "PALACE ELITE",
    "SALE_DTE": "2017-12-04T00:00:00",
    "USG_DTE": "2021-02-08T00:00:00",
    "ADDRESS": "",
    "CITY": "",
    "STATE": "",
    "ZIP": "",
    "CNTRY": "",
    "TEL": "",
    "USG_PLACE": " ",
    "MPAYS": 0.0,
    "USG_TEMP": "G",
    "VENC_YRS": 5.0,
    "SALIDA": " ",
    "APP_AMIGO": "",
    "KIND": "",
    "HOTEL": "",
    "HOTFOLIO": 0,
    "RM_TYPE": "",
    "ARV_DATE": "0001-01-01T00:00:00",
    "STATUS": "S",
    "INVOICE": "",
    "VALIDYRS": 0,
    "VALIDDTE": "2022-12-04T00:00:00",
    "IDCHECKIN": 14110004,
    "CONTRACT": " ",
    "IGR": "N",
    "IGRN": 0.0,
    "IGRTYPEWK": "",
    "IGRFOLIOWK": 0.0,
    "TAR_PAGADA": 0.00,
    "INVOICEDTE": "0001-01-01T00:00:00",
    "FOLIOAIRT": " ",
    "CO_AMIGO": 0.0,
    "REWARDDATE": "0001-01-01T00:00:00",
    "WEEK52": "N",
    "STOCK_WEEK": "N",
    "STOCK_WK_TYPE": "",
    "GR_INCLUDE": 0,
    "ULG_INCLUDE": "N",
    "ULG_AMOUNT": 0.00,
    "ULG_MAX_PERS": 0.00,
    "PROJECTID": 6,
    "TYPENAME": "ANNIVERSARY WEEK(S) ",
    "WEEK52_START_YEAR": 0,
    "WEEK52_VALIDITY_YEARS": 0,
    "ChristmasBonus": false,
    "ADDITIONALBENEFITS": null,
    "Stock": null,
    "StockUnit": null,
    "IncentiveWeek": null,
    "Cash_sale": null,
    "NumberExtraValidityYears": 0,
    "IsIncongruos": false,
    "StockExtraValidityYears": false,
    "ULG_ADDITIONAL_PAYMENT": false,
    "MinimumOccupancy": 0.0,
    "MaximumOccupancy": 0.0,
    "ReplacementType": 0
  },
];
