export default [
  {
    AditionalCharges: 0,
    AmountThanksGiving: 0,
    AmountOutOfSeason: 0,
    Hotel: 'BP',
    Folio: 0,
    Company: 5,
    Application: '4044216',
    MarketExtra: '',
    RateTypeExtra: '',
    OriginRsv: 'CLV',
    TypeBooking: 0,
    TypeGolf: 'AINC',
    ProvisionToChange: '',
    ProvisionToChangeComplement: '',
    TotalProvisToChange: 0,
    TotalProvisToChangeComplement: 0,
    TypeCombination: '',
    AdditionalCost: 0,
    RsvPromotion: 0,
    RsvCategory: '2',
    RecnumDiamondPromotion: 0,
    GolfRateType: 0,
    IsTravelInsurance: false,
    FreeUpGrade: false,
    MarketFee: 0,
    RsvPromotionId: 0,
    Refundable: false,
    ProductType: 'W',
    TemporalBenefit: ''
  },
  {},
  {},
  {}
]
