export default {
  "__type": "PalaceResorts.Messages.CreditoCobranzaReserva.InfoMemberProvision",
  "Agency_cd_ext": "PEL-IMP",
  "Agency_cd_nac": "M/PEL-IM",
  "Contract_ext": "",
  "Contract_nac": "SEMANA(S) IMPERIAL(A",
  "Cdeaccshtl": "",
  "Cdeaccsglf": "",
  "Accesshotel": "",
  "Accessgolf": "",
  "NumberAirfare": "",
  "PriceAirfare": 0,
  "AmountTaxFee": 0,
  "Category": "IMPWKS",
  "IsLBC": false,
  "IsResidence": false,
  "ProvPack": 0,
  "ExceededAirfare": 0,
  "TaxFeeProvis": 0,
  "CostProvis": 0,
  "AccessThanksGiving": true,
  "IsRestrictUse": false,
  "RECNUM": 1550626,
  "COMPANY": 5,
  "APPLICATION": "4081905",
  "TYPE": "H2",
  "FOLIO": 19538,
  "FIRST": "ALBERTO",
  "LAST": "TELLEZ",
  "SALE_DTE": "/Date(1665723600000)/",
  "USG_DTE": "/Date(-62135575200000)/",
  "ADDRESS": "",
  "CITY": "",
  "STATE": "",
  "ZIP": "",
  "CNTRY": "",
  "TEL": "",
  "USG_PLACE": " ",
  "MPAYS": 0,
  "USG_TEMP": "G",
  "VENC_YRS": 11,
  "SALIDA": " ",
  "APP_AMIGO": "",
  "KIND": "",
  "HOTEL": "",
  "HOTFOLIO": 0,
  "RM_TYPE": "",
  "ARV_DATE": "/Date(-62135575200000)/",
  "STATUS": "A",
  "INVOICE": "",
  "VALIDYRS": 0,
  "VALIDDTE": "/Date(2012878800000)/",
  "IDCHECKIN": 0,
  "CONTRACT": " ",
  "IGR": "N",
  "IGRN": 0,
  "IGRTYPEWK": "",
  "IGRFOLIOWK": 0,
  "TAR_PAGADA": 0,
  "INVOICEDTE": "/Date(-62135575200000)/",
  "FOLIOAIRT": " ",
  "CO_AMIGO": 0,
  "REWARDDATE": "/Date(-62135575200000)/",
  "WEEK52": "N",
  "STOCK_WEEK": "N",
  "STOCK_WK_TYPE": "",
  "GR_INCLUDE": 0,
  "ULG_INCLUDE": "N",
  "ULG_AMOUNT": 0,
  "ULG_MAX_PERS": 0,
  "PROJECTID": 6,
  "TYPENAME": "IMPERIAL WEEK(S) PEU P.R. - JAM",
  "WEEK52_START_YEAR": 0,
  "WEEK52_VALIDITY_YEARS": 0,
  "ChristmasBonus": false,
  "ADDITIONALBENEFITS": null,
  "Stock": null,
  "StockUnit": null,
  "IncentiveWeek": null,
  "Cash_sale": null,
  "NumberExtraValidityYears": 0,
  "IsIncongruos": false,
  "StockExtraValidityYears": false,
  "ULG_ADDITIONAL_PAYMENT": false,
  "MinimumOccupancy": 0,
  "MaximumOccupancy": 0,
  "ReplacementType": 0
}
