export default {
  __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.InfoUserMember',
  UserMember: {
    __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.UserMember',
    Recnum: 0,
    Application: '4044216',
    Company: 5,
    Project: '6',
    Password: '',
    First_name: 'PRUEBAS NUEVO ESQUEMA',
    Last_name: 'DE EXTENSIONES',
    Birth_date: '0001-01-01T06:00:00.000Z',
    Membership_status: 'Active',
    Physical_address: '',
    Marital_status: '',
    Spouse_name: '',
    Spouse_birth: '0001-01-01T06:00:00.000Z',
    Spouse_email: '',
    Child_name: '',
    Child_birth: '0001-01-01T06:00:00.000Z',
    Favourite_palace_resort: '',
    Best_time_travel: 0,
    Rank_preference_1: '',
    Rank_preference_2: '',
    Rank_preference_3: '',
    Rank_preference_4: '',
    Rank_preference_5: '',
    Rank_preference_6: '',
    Rank_preference_7: '',
    Rank_preference_8: '',
    Rank_preference_9: '',
    Rank_preference_10: '',
    Profile_photo: '',
    Background_set: '',
    Style_set: '',
    Lastlogin: '0001-01-01T06:00:00.000Z',
    Email: 'amex@palaceresorts.com',
    Sendpromotions: false,
    Createdate: '0001-01-01T06:00:00.000Z',
    Status: 1,
    Modif_fecha: '0001-01-01T06:00:00.000Z',
    Modif_user: '',
    Isnational: false,
    ReservationAllowed: false,
    Culture: 'en-US',
    CancelDesc: '',
    MembershipLevel: 'RE',
    LevelDescription: 'RESIDENCE',
    Lang: 'E'
  },
  Name: 'PRUEBAS NUEVO ESQUEMA DE EXTENSIONES',
  IsInternetUser: false,
  SaleDate: '2019-06-20T05:00:00.000Z',
  ReservationCostType: 'V',
  MemberRateType: 'H',
  Market: 'USA'
}
