export default {
  selected: true,
  disabled: false,
  text: 'ABIGAIL CORREA',
  __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.InfoMemberProfileRelated',
  Leveldescription: 'RESIDENCE',
  DescPromoRef: '',
  LevelCodeDescription: 'RE-RESIDENCE',
  _recnum_profile: 650535,
  company: 5,
  application: '4044216',
  name: 'ABIGAIL CORREA',
  idrelacionclub: 999999,
  relationship: 4,
  idprofileopera: '20743585',
  statusmembresia: 'A',
  membertype: 'PEF',
  memberlevel: 'RE',
  statusprofile: 'A',
  firstname: 'ABIGAIL',
  lastname: 'CORREA',
  IsNational: false,
  idprofileoperajc: '',
  Zip: '',
  City: 'HIALEAH GARDENS',
  Country: 'US',
  Language: 'E',
  Tel: '1-305-',
  email: 'jreyes@palaceresorts.com',
  relationdescription: 'Guest',
  InReferral: 2,
  confirmationemail: 0,
  password: '',
  MemberProfileImage: '',
  resetpassword: 0,
  SocialSecurityNumber: '',
  relationshipName: 'Guest',
  labelColor: 'default',
  id: '20743585',
  html: "ABIGAIL CORREA <span class='label label-default pull-right'>Guest</span>",
  element: {}
}
