const reservationRateCodesMock: any = []
reservationRateCodesMock['CNG'] = [
  [
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-11T06:00:00.000Z',
      Depart_dt: '2022-11-11T06:00:00.000Z',
      Rate: 452.62,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 452.62,
      AdditionalCost: 0,
      RateOperaUpdated: 452.62,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-12T06:00:00.000Z',
      Depart_dt: '2022-11-12T06:00:00.000Z',
      Rate: 452.62,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 452.62,
      AdditionalCost: 0,
      RateOperaUpdated: 452.62,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-13T06:00:00.000Z',
      Depart_dt: '2022-11-13T06:00:00.000Z',
      Rate: 452.62,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 452.62,
      AdditionalCost: 0,
      RateOperaUpdated: 452.62,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-14T06:00:00.000Z',
      Depart_dt: '2022-11-14T06:00:00.000Z',
      Rate: 438.62,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 438.62,
      AdditionalCost: 0,
      RateOperaUpdated: 438.62,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 5,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-15T06:00:00.000Z',
      Depart_dt: '2022-11-15T06:00:00.000Z',
      Rate: 382.16,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 382.16,
      AdditionalCost: 0,
      RateOperaUpdated: 382.16,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -42.462,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-16T06:00:00.000Z',
      Depart_dt: '2022-11-16T06:00:00.000Z',
      Rate: 382.16,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 382.16,
      AdditionalCost: 0,
      RateOperaUpdated: 382.16,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -42.462,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-17T06:00:00.000Z',
      Depart_dt: '2022-11-17T06:00:00.000Z',
      Rate: 382.16,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2942.96,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 382.16,
      AdditionalCost: 0,
      RateOperaUpdated: 382.16,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -42.462,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    }
  ],
  0,
  0,
  0
]
reservationRateCodesMock['CNG_NR'] = [
  [
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-11T06:00:00.000Z',
      Depart_dt: '2022-11-11T06:00:00.000Z',
      Rate: 429.99,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 429.99,
      AdditionalCost: 0,
      RateOperaUpdated: 429.99,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.631,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-12T06:00:00.000Z',
      Depart_dt: '2022-11-12T06:00:00.000Z',
      Rate: 429.99,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 429.99,
      AdditionalCost: 0,
      RateOperaUpdated: 429.99,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.631,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-13T06:00:00.000Z',
      Depart_dt: '2022-11-13T06:00:00.000Z',
      Rate: 429.99,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 429.99,
      AdditionalCost: 0,
      RateOperaUpdated: 429.99,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.631,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-14T06:00:00.000Z',
      Depart_dt: '2022-11-14T06:00:00.000Z',
      Rate: 416.69,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 416.69,
      AdditionalCost: 0,
      RateOperaUpdated: 416.69,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 5,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.931,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-15T06:00:00.000Z',
      Depart_dt: '2022-11-15T06:00:00.000Z',
      Rate: 363.05,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 363.05,
      AdditionalCost: 0,
      RateOperaUpdated: 363.05,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.231,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.3389,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-16T06:00:00.000Z',
      Depart_dt: '2022-11-16T06:00:00.000Z',
      Rate: 363.05,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 363.05,
      AdditionalCost: 0,
      RateOperaUpdated: 363.05,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.231,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.3389,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-17T06:00:00.000Z',
      Depart_dt: '2022-11-17T06:00:00.000Z',
      Rate: 363.05,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2795.81,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 363.05,
      AdditionalCost: 0,
      RateOperaUpdated: 363.05,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.231,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.3389,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    }
  ],
  0,
  0,
  0
]
reservationRateCodesMock['PS1'] = [0, 0, 0, 0]
reservationRateCodesMock['PS1_LOCKOFF'] = [0, 0, 0, 0]
reservationRateCodesMock['PS1_LOCKOFF_NR'] = [0, 0, 0, 0]
reservationRateCodesMock['SUP'] = [
  [
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-11T06:00:00.000Z',
      Depart_dt: '2022-11-11T06:00:00.000Z',
      Rate: 450.66,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 450.66,
      AdditionalCost: 0,
      RateOperaUpdated: 450.66,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-12T06:00:00.000Z',
      Depart_dt: '2022-11-12T06:00:00.000Z',
      Rate: 450.66,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 450.66,
      AdditionalCost: 0,
      RateOperaUpdated: 450.66,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-13T06:00:00.000Z',
      Depart_dt: '2022-11-13T06:00:00.000Z',
      Rate: 450.66,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 450.66,
      AdditionalCost: 0,
      RateOperaUpdated: 450.66,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-14T06:00:00.000Z',
      Depart_dt: '2022-11-14T06:00:00.000Z',
      Rate: 436.72,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 436.72,
      AdditionalCost: 0,
      RateOperaUpdated: 436.72,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 5,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: '',
          description: '',
          factor_value: 0,
          idrate_factor_type: '',
          amount_promotion: 0,
          idrate_promotion: 0,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-15T06:00:00.000Z',
      Depart_dt: '2022-11-15T06:00:00.000Z',
      Rate: 380.51,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 380.51,
      AdditionalCost: 0,
      RateOperaUpdated: 380.51,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -42.279,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-16T06:00:00.000Z',
      Depart_dt: '2022-11-16T06:00:00.000Z',
      Rate: 380.51,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 380.51,
      AdditionalCost: 0,
      RateOperaUpdated: 380.51,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -42.279,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-17T06:00:00.000Z',
      Depart_dt: '2022-11-17T06:00:00.000Z',
      Rate: 380.51,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2930.23,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 380.51,
      AdditionalCost: 0,
      RateOperaUpdated: 380.51,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -42.279,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    }
  ],
  0,
  0,
  0
]
reservationRateCodesMock['JOF'] = [
  [
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-11T06:00:00.000Z',
      Depart_dt: '2022-11-11T06:00:00.000Z',
      Rate: 428.13,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 428.13,
      AdditionalCost: 0,
      RateOperaUpdated: 428.13,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.533,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-12T06:00:00.000Z',
      Depart_dt: '2022-11-12T06:00:00.000Z',
      Rate: 428.13,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 428.13,
      AdditionalCost: 0,
      RateOperaUpdated: 428.13,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.533,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-13T06:00:00.000Z',
      Depart_dt: '2022-11-13T06:00:00.000Z',
      Rate: 428.13,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 428.13,
      AdditionalCost: 0,
      RateOperaUpdated: 428.13,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.533,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-14T06:00:00.000Z',
      Depart_dt: '2022-11-14T06:00:00.000Z',
      Rate: 414.88,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 414.88,
      AdditionalCost: 0,
      RateOperaUpdated: 414.88,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 5,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.836000000000002,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-15T06:00:00.000Z',
      Depart_dt: '2022-11-15T06:00:00.000Z',
      Rate: 361.49,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 361.49,
      AdditionalCost: 0,
      RateOperaUpdated: 361.49,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.1395,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.16505000000001,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-16T06:00:00.000Z',
      Depart_dt: '2022-11-16T06:00:00.000Z',
      Rate: 361.49,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 361.49,
      AdditionalCost: 0,
      RateOperaUpdated: 361.49,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.1395,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.16505000000001,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-17T06:00:00.000Z',
      Depart_dt: '2022-11-17T06:00:00.000Z',
      Rate: 361.49,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 361.49,
      AdditionalCost: 0,
      RateOperaUpdated: 361.49,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.1395,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.16505000000001,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    }
  ],
  0,
  0,
  0
]
reservationRateCodesMock['JOF_NR'] = [
  [
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-11T06:00:00.000Z',
      Depart_dt: '2022-11-11T06:00:00.000Z',
      Rate: 428.13,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 428.13,
      AdditionalCost: 0,
      RateOperaUpdated: 428.13,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.533,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-12T06:00:00.000Z',
      Depart_dt: '2022-11-12T06:00:00.000Z',
      Rate: 428.13,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 428.13,
      AdditionalCost: 0,
      RateOperaUpdated: 428.13,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.533,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-13T06:00:00.000Z',
      Depart_dt: '2022-11-13T06:00:00.000Z',
      Rate: 428.13,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 428.13,
      AdditionalCost: 0,
      RateOperaUpdated: 428.13,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 6,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -22.533,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-14T06:00:00.000Z',
      Depart_dt: '2022-11-14T06:00:00.000Z',
      Rate: 414.88,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 414.88,
      AdditionalCost: 0,
      RateOperaUpdated: 414.88,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 5,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.836000000000002,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-15T06:00:00.000Z',
      Depart_dt: '2022-11-15T06:00:00.000Z',
      Rate: 361.49,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 361.49,
      AdditionalCost: 0,
      RateOperaUpdated: 361.49,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.1395,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.16505000000001,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-16T06:00:00.000Z',
      Depart_dt: '2022-11-16T06:00:00.000Z',
      Rate: 361.49,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 361.49,
      AdditionalCost: 0,
      RateOperaUpdated: 361.49,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.1395,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.16505000000001,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    },
    {
      __type: {
        __type: 'PalaceResorts.Messages.CreditoCobranzaReserva.RmFolioRCDetail'
      },
      Recnum: 0,
      Hotel: '',
      Folio: 0,
      Application: '',
      Company: 0,
      RateCode: 'SOCIOS',
      Arv_date: '2022-11-17T06:00:00.000Z',
      Depart_dt: '2022-11-17T06:00:00.000Z',
      Rate: 361.49,
      ProvisionID: '',
      ProvisionFol: 0,
      AmountOutOfSeason: 0,
      AmountThanksGivingDay: 0,
      AmountWeek52: 0,
      AmountResortAccess: 0,
      AmountChargeUpgrade: 0,
      AditionalCharges: 0,
      GolfRate: 0,
      Deposit: 2783.74,
      HasChanged: false,
      IsDeleted: false,
      IsImperialWeek: false,
      Contract: '0',
      Agency: 'PR-ELITE',
      Category: 'EP',
      Market: '',
      RateType: '',
      IsPackExtra: false,
      PriceWithoutDiscount: 0,
      Discount: 0,
      RateOpera: 361.49,
      AdditionalCost: 0,
      RateOperaUpdated: 361.49,
      PackageCode: '',
      PackageUnitAmount: 0,
      PromotionCode: '',
      Description: '',
      FactorValue: 0,
      IdRateFactorType: '',
      AmountPromotion: 0,
      RateCodeCLV: 'CLT',
      CleverCodeBase: 'CLT',
      HasError: false,
      Exception: null,
      Layer: 4,
      CostDayResidenceFee: 0,
      FeeCID: 0,
      PromotionList: [
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YMNR',
          description: 'YMNR',
          factor_value: -5,
          idrate_factor_type: 'NON_REFUNDABLE_PERCENTAGE',
          amount_promotion: -21.1395,
          idrate_promotion: 42717,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        },
        {
          Recnum: 0,
          RecnumRcDetail: 0,
          Folio: 0,
          Hotel: '',
          promotion_code: 'YM_NOV',
          description: 'NOVIEMBRE,2022',
          factor_value: -10,
          idrate_factor_type: 'PERCENTAGE',
          amount_promotion: -40.16505000000001,
          idrate_promotion: 116612,
          creation_date: '2001-01-01T07:03:58.000Z',
          IsDelete: false
        }
      ],
      CreationDate: '2001-01-01T07:03:58.000Z'
    }
  ],
  0,
  0,
  0
]

export default reservationRateCodesMock
