export interface UserMember {
  _recnum: number
  _application: string
  _company: number
  _project: string
  _password: string
  _first_name: string
  _last_name: string
  _birth_string: string
  _membership_status: string
  _physical_address: string
  _marital_status: string
  _spouse_name: string
  _spouse_birth: string
  _spouse_email: string
  _child_name: string
  _child_birth: string
  _favourite_palace_resort: string
  _best_time_travel: number
  _rank_preference_1: string
  _rank_preference_2: string
  _rank_preference_3: string
  _rank_preference_4: string
  _rank_preference_5: string
  _rank_preference_6: string
  _rank_preference_7: string
  _rank_preference_8: string
  _rank_preference_9: string
  _rank_preference_10: string
  _profile_photo: string
  _background_set: string
  _style_set: string
  _lastlogin: string
  _email: string
  _sendpromotions: boolean
  _createstring: string
  _isnational: boolean
  _status: number
  _modif_fecha: string
  _modif_user: string
  _ReservationAllowed: boolean
  _culture: string
  _cancelDesc: string
  _membershiplevel: string
  _leveldescription: string
  _lang: string
  _isIHR: boolean
}
