export interface UserMember {
  Recnum: number
  Application: string
  Company: number
  Project: string
  Password: string
  First_name: string
  Last_name: string
  Birth_string: string
  Membership_status: string
  Physical_address: string
  Marital_status: string
  Spouse_name: string
  Spouse_birth: string
  Spouse_email: string
  Child_name: string
  Child_birth: string
  Favourite_palace_resort: string
  Best_time_travel: number
  Rank_preference_1: string
  Rank_preference_2: string
  Rank_preference_3: string
  Rank_preference_4: string
  Rank_preference_5: string
  Rank_preference_6: string
  Rank_preference_7: string
  Rank_preference_8: string
  Rank_preference_9: string
  Rank_preference_10: string
  Profile_photo: string
  Background_set: string
  Style_set: string
  Lastlogin: string
  Email: string
  Sendpromotions: boolean
  Createstring: string
  Isnational: boolean
  Status: number
  Modif_fecha: string
  Modif_user: string
  ReservationAllowed: boolean
  Culture: string
  CancelDesc: string
  Membershiplevel: string
  Leveldescription: string
  Lang: string
}
