export enum CategoryFilters {
  STATUS = 0,
  WEEKS = 1,
  ALL = 'All',
  SORT_ASC = '0',
  SORT_DESC = '1',
  EXPIRED = 'EXPIRED',
  USED = 'USED',
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  TORELEASE = 'TO RELEASE',
  IMPERIALWEEK = 'IMPERIAL WEEK',
  IMPERIALNIGHT = 'IMPERIAL NIGHT',
  ANNIVERSARYWEEK = 'ANNIVERSARY WEEK',
  BONUSWEEK = 'BONUS WEEK',
  INCENTIVEWEEK = 'INCENTIVE WEEK',
  INCENTIVENIGHT = 'INCENTIVE NIGHT'
}
