import ReservationsDto from '../dto/reservationsDto'

export default function ReservationDtoFactory(): ReservationsDto {
  return {
    company: '',
    application: '',
    ent_date: '',
    hotel: '',
    folioClub: '',
    status: '',
    first_name: '',
    firstName: '',
    last_name: '',
    lastName: '',
    nights: '',
    rm_type: '',
    arv_date: '',
    ent_time: '',
    arvDate: '',
    depart_dt: '',
    departDt: '',
    rooms: '',
    adult: '',
    child: '',
    kid: '',
    baby: '',
    resort: '',
    xtra_adu: '',
    xtra_chd: '',
    xtra_kid: '',
    totalReserv: '',
    category: '',
    categoryId: '',
    balance: '',
    Paid: '',
    Refundable: '',
    tipo: '',
    sendPaymentLink: false,
    showCountdown: false
  }
}
