export interface ReservationCompanionResponse{
  Recnum: number;
  Hotel: string;
  IdProfile: string;
  Type: string;
  Folio: string;
  _recnum_profile: number;
  company: number;
  application: string;
  name: string;
  idrelacionclub: number;
  relationship: number;
  idprofileopera: string;
  statusmembresia: string;
  membertype: string;
  memberlevel: string;
  statusprofile: string;
  firstname: string;
  lastname: string;
  IsNational: false,
  idprofileoperajc: string;
  Zip: string;
  City: string;
  Country: string;
  Language: string;
  Tel: string;
  email: string;
  relationdescription: string;
  InReferral: number;
  confirmationemail: number;
  password: string;
  MemberProfileImage: string;
  resetpassword: number;
  SocialSecurityNumber: string;
}

export interface ReservationResponse{
  RecNum: number;
  Hotel: string;
  Hotel_Name: string;
  Folio: number;
  Last_name: string;
  First_name: string;
  Type: string;
  Mail_name: string;
  Agency_cd: string;
  Agency_name: string;
  Ded_comm: string;
  Mkt_seg: string;
  Company: string;
  Member: string;
  Nationality: string;
  Arv_date: string;
  Nights: number;
  Depart_dt: string;
  Rooms: number;
  Rm_type: string;
  Rm_desc: string;
  Room: string;
  Share: string;
  Rel_folio: number;
  Rate: number;
  Adult: number;
  Child: number;
  Address: string;
  City: string;
  State: string;
  Country: string;
  Zip: string;
  Phone: string;
  Co_address: string;
  Co_city: string;
  Co_state: string;
  Co_country: string;
  Co_zip: string;
  Co_phone: string;
  Deposit: number;
  Rate1: number;
  Year: number;
  Week: number;
  Companions: ReservationCompanionResponse[];
}

export interface CreateNewReservationResponseDto {
  MarkAsPrincipalDiamond: boolean;
  UnlinkReservationDiamond: boolean;
  RecnumPromotions: any;
  pay: number;
  Reservation: ReservationResponse;
  Reservations: ReservationResponse[];
}
