export enum BookingProvotionStatus {
  PREFERENCIAL = 'PREFERENCIAL',
  REFERIDO = 'REFERIDOS',
  IMP_WEEKS = 'IMP WEEKS',
  BONO = 'BONO',
  ANIVERSARIO = 'ANIVERSARIO',
  INCENTIVA = 'INCENTIVA',
  REWARDS = 'REWARDS',
  MOVE_IN = 'MOVE IN',
  IMP_NIGHT = 'IMP NIGHT'
}
