export enum BookingStatus {
  ON_HOLD = 'ON HOLD',
  PENDING_PAYMENT = 'PENDING PAYMENT',
  PAYMENT_PENDING = 'PAYMENT PENDING',
  PENDING = 'PENDING',
  TO_VALIDATE = 'TO VALIDATE',
  TRF = 'TO VALIDATE',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  PAST = 'PAST',
  ON_PROCESS = 'ON_PROCESS'
}
